### ISSUE TITLE
NPM 401 Error

### ISSUE THREAD

**Issue by thomasconner** [primer/publish#27]
[This recent change](https://github.com/primer/publish/pull/25) to the npm registry url causes `npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/<package-name> - You must be logged in to publish packages.`

Although the url looks correct it doesn't seem to work anymore when using and `NPM_AUTH_TOKEN`.

**Comment by tarunmangukiya** [comment]
I am facing same error!

**Comment by cinderblock** [comment]
If I remove `NPM_AUTH_TOKEN` [I get an error saying that the token is required](https://github.com/cinderblock/python-rencode/commit/7b9840cd8fb95446842cf0fbefdf9daee523e76c/checks?check_suite_id=373560292).

If I leave it in, [I get the 401 error](https://github.com/cinderblock/python-rencode/commit/0fadae8a4f92b7f1564153c91173298ceb95ff2b/checks?check_suite_id=373547897).

**Comment by cinderblock** [comment]
I was able to fix this problem by specifying an extra environment variable:

```yml
NPM_REGISTRY_URL: registry.npmjs.org
```

### Alternate Fix
Since this problem is only on master *(it's bad practice to depend on master anyway)*
```yml
uses: primer/publish@master
```
becomes
```yml
uses: primer/publish@v2.0.0
```

## The Problem

A [recent change](https://github.com/primer/publish/commit/6f503e6a66c5eabb48f837ec618845b721ed290a) added an `https://` in front of a URL which does not match the [npm docs](https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow).

### Expected
```txt
//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
```
### Created
```txt
//https://registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}
```

### Follow up

However now there is another warning because the next line of the created `.npmrc` does expect the `https://` prefix. This, I presume, was the impetus for the offending change.

**Comment by ricar2ce** [comment]
just run:
`npm login`
then give the request data and enjoy
sory for my english
